apps/reports/api/urls.py
from django.urls import path
from .views import RegisterEditAPIView, RegistersListApiView, RegisterDeleteAPIView


urlpatterns = [
    path('registers/', RegistersListApiView.as_view(),
         name='register-list'),
    path('register/<int:pk>/', RegistersListApiView.as_view(),
         name='register'),
    path('update/<int:pk>/', RegisterEditAPIView.as_view(), name='registers-list'),
    path('delete/<int:pk>/', RegisterDeleteAPIView.as_view()),
]

apps/reports/urls.py
from django.urls import path, include

from .views import RegistersListView, UpdateRegisterView, DeleteRegisterView, BaseView, AboutView, IntroductionView

app_name = 'reports'

urlpatterns = [
    path('', IntroductionView.as_view(), name='introduction'),
    path('report/', RegistersListView.as_view(), name='index'),
    path('base/', BaseView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('update/<int:pk>', UpdateRegisterView.as_view(), name='update'),
    path('delete/<int:pk>', DeleteRegisterView.as_view(), name='delete'),
    path('api/', include('apps.reports.api.urls')),
]

covid_report/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("apps.reports.urls")),
]

apps/reports/models.py
from django.db import models


class Country(models.Model):
    country = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.country

    class Meta:
        verbose_name_plural = 'Countries'


class Register(models.Model):

    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    total_cases = models.IntegerField(default=0)
    new_cases = models.IntegerField(default=0)
    total_deaths = models.IntegerField(default=0)
    new_deaths = models.IntegerField(default=0)
    total_recovered = models.IntegerField(default=0)
    new_recovered = models.IntegerField(default=0)
    active_cases = models.IntegerField(default=0)
    serious_critical = models.IntegerField(default=0)
    total_cases_per_million = models.IntegerField(default=0)
    deaths_per_million = models.IntegerField(default=0)
    total_tests = models.IntegerField(default=0)
    tests_per_million = models.IntegerField(default=0)
    population = models.IntegerField(default=0)

    def __str__(self):
        return self.country.country

apps/reports/forms.py
from django import forms

from .models import Register


class RegisterForm(forms.ModelForm):

    total_cases = forms.IntegerField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-3'}))
    total_deaths = forms.IntegerField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-3'}))
    new_recovered = forms.IntegerField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-3'}))
    active_cases = forms.IntegerField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-3'}))
    serious_critical = forms.IntegerField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-3'}))
    new_cases = forms.IntegerField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-3'}))
    new_deaths = forms.IntegerField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-3'}))
    total_recovered = forms.IntegerField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-3'}))
    total_cases_per_million = forms.IntegerField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-3'}))
    deaths_per_million = forms.IntegerField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-3'}))
    total_tests = forms.IntegerField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-3'}))
    tests_per_million = forms.IntegerField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-3'}))
    population = forms.IntegerField(widget=forms.TextInput(
        attrs={'class': 'form-control mb-3'}))

    class Meta:
        model = Register
        fields = [
            'total_cases',
            'total_deaths',
            'new_recovered',
            'active_cases',
            'serious_critical',
            'new_cases',
            'total_recovered',
            'new_deaths',
            'total_cases_per_million',
            'deaths_per_million',
            'total_tests',
            'tests_per_million',
            'population',
        ]

apps/reports/api/views.py
from datetime import date
from django.http import Http404
from yaml import serialize
from rest_framework.views import APIView
from rest_framework.generics import ListAPIView
from rest_framework.response import Response
from rest_framework import status

from apps.reports.models import Register
from .seralizers import RegistersSerializer


class RegistersListApiView(ListAPIView):

    serializer_class = RegistersSerializer
    queryset = Register.objects.all()

    def get_queryset(self):
        pk = self.kwargs.get('pk', None)
        if(pk):
            register = Register.objects.filter(pk=pk, date=date.today())
        else:
            register = Register.objects.all()
        return register


class RegisterEditAPIView(APIView):

    def put(self, request, pk, format=None):
        registers = Register.objects.get(pk=pk)
        serializer = RegistersSerializer(registers, data=request.data)

        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class RegisterDeleteAPIView(APIView):

    def delete(self, request, pk, format=None):
        registers = Register.objects.get(pk=pk)
        registers.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

apps/reports/views.py
import requests

from datetime import date
from .models import Register
from django.views.generic import ListView, UpdateView, TemplateView
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.conf import settings


class BaseView(TemplateView):
    template_name = 'base.html'


class RegistersListView(ListView):
    model = Register
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['registers'] = Register.objects.filter(date=date.today())
        return context


class UpdateRegisterView(UpdateView):
    template_name = 'update.html'
    form_class = RegisterForm
    model = Register

    def post(self, request, pk):
        data = request.POST
        url = f"{settings.BASE_URL}update/{pk}/"
        country = Register.objects.filter(pk=pk).first().country.id
        try:
            body = {
                "total_cases": int(data['total_cases']),
                "new_cases": int(data['new_cases']),
                "total_deaths": int(data['total_deaths']),
                "new_deaths": int(data['new_deaths']),
                "total_recovered": int(data['total_recovered']),
                "active_cases": int(data['active_cases']),
                "serious_critical": int(data['serious_critical']),
                "total_cases_per_million": int(data['total_cases_per_million']),
                "deaths_per_million": int(data['deaths_per_million']),
                "total_tests": int(data['total_tests']),
                "tests_per_million": int(data['tests_per_million']),
                "population": int(data['population']),
                "country": country,
            }
            requests.put(url, data=body)
        except Exception as e:
            print(e)
        return redirect("/report/")


class DeleteRegisterView(TemplateView):

    def get(self, _, pk):
        url = f"{settings.BASE_URL}delete/{pk}/"
        try:
            requests.delete(url)
        except Exception as e:
            print(e)
        return redirect("/report/")


class IntroductionView(TemplateView):
    template_name = 'introduction.html'


class AboutView(TemplateView):
    template_name = 'about.html'

templates/about.html
{% extends 'base.html' %} {% load static %} {% block title %}About Us - Covid
Report {% endblock %} {% block content %}
<div class="min-height-200px">
  <div class="row justify-content-center">
    <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 mb-30">
      <div class="pd-20 card-box height-100-p">
        <div class="profile-photo">
          <img
            src="{% static 'vendors/images/photo1.jpg' %}"
            alt=""
            class="avatar-photo"
          />
          <div
            class="modal fade"
            id="modal"
            tabindex="-1"
            role="dialog"
            aria-labelledby="modalLabel"
            aria-hidden="true"
          >
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-body pd-5">
                  <div class="img-container">
                    <img
                      id="image"
                      src="vendors/images/photo2.jpg"
                      alt="Picture"
                    />
                  </div>
                </div>
                <div class="modal-footer">
                  <input type="submit" value="Update" class="btn btn-primary" />
                  <button
                    type="button"
                    class="btn btn-default"
                    data-dismiss="modal"
                  >
                    Close
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <h5 class="text-center h5 mb-0">Isaac Benavides</h5>
        <p class="text-center text-muted font-14">CAR IV</p>
        <div class="profile-info">
          <h5 class="mb-20 h5 text-blue">Contact Information</h5>
          <ul>
            <li>
              <span>Email Address:</span>
              FerdinandMChilds@test.com
            </li>
            <li>
              <span>Phone Number:</span>
              619-229-0054
            </li>
            <li>
              <span>Country:</span>
              America
            </li>
            <li>
              <span>Address:</span>
              1807 Holden Street<br />
              San Diego, CA 92115
            </li>
          </ul>
        </div>
        <div class="profile-social">
          <h5 class="mb-20 h5 text-blue">Social Links</h5>
          <ul class="clearfix">
            <li>
              <a
                href="#"
                class="btn"
                data-bgcolor="#3b5998"
                data-color="#ffffff"
                ><i class="fa fa-facebook"></i
              ></a>
            </li>
            <li>
              <a
                href="#"
                class="btn"
                data-bgcolor="#1da1f2"
                data-color="#ffffff"
                ><i class="fa fa-twitter"></i
              ></a>
            </li>
            <li>
              <a
                href="#"
                class="btn"
                data-bgcolor="#007bb5"
                data-color="#ffffff"
                ><i class="fa fa-linkedin"></i
              ></a>
            </li>
            <li>
              <a
                href="#"
                class="btn"
                data-bgcolor="#f46f30"
                data-color="#ffffff"
                ><i class="fa fa-instagram"></i
              ></a>
            </li>
            <li>
              <a
                href="#"
                class="btn"
                data-bgcolor="#c32361"
                data-color="#ffffff"
                ><i class="fa fa-dribbble"></i
              ></a>
            </li>
            <li>
              <a
                href="#"
                class="btn"
                data-bgcolor="#3d464d"
                data-color="#ffffff"
                ><i class="fa fa-dropbox"></i
              ></a>
            </li>
            <li>
              <a
                href="#"
                class="btn"
                data-bgcolor="#db4437"
                data-color="#ffffff"
                ><i class="fa fa-google-plus"></i
              ></a>
            </li>
            <li>
              <a
                href="#"
                class="btn"
                data-bgcolor="#bd081c"
                data-color="#ffffff"
                ><i class="fa fa-pinterest-p"></i
              ></a>
            </li>
            <li>
              <a
                href="#"
                class="btn"
                data-bgcolor="#00aff0"
                data-color="#ffffff"
                ><i class="fa fa-skype"></i
              ></a>
            </li>
            <li>
              <a
                href="#"
                class="btn"
                data-bgcolor="#00b489"
                data-color="#ffffff"
                ><i class="fa fa-vine"></i
              ></a>
            </li>
          </ul>
        </div>
        <div class="profile-skills">
          <h5 class="mb-20 h5 text-blue">Key Skills</h5>
          <h6 class="mb-5 font-14">HTML</h6>
          <div class="progress mb-20" style="height: 6px">
            <div
              class="progress-bar"
              role="progressbar"
              style="width: 90%"
              aria-valuenow="0"
              aria-valuemin="0"
              aria-valuemax="100"
            ></div>
          </div>
          <h6 class="mb-5 font-14">Css</h6>
          <div class="progress mb-20" style="height: 6px">
            <div
              class="progress-bar"
              role="progressbar"
              style="width: 70%"
              aria-valuenow="0"
              aria-valuemin="0"
              aria-valuemax="100"
            ></div>
          </div>
          <h6 class="mb-5 font-14">jQuery</h6>
          <div class="progress mb-20" style="height: 6px">
            <div
              class="progress-bar"
              role="progressbar"
              style="width: 60%"
              aria-valuenow="0"
              aria-valuemin="0"
              aria-valuemax="100"
            ></div>
          </div>
          <h6 class="mb-5 font-14">Bootstrap</h6>
          <div class="progress mb-20" style="height: 6px">
            <div
              class="progress-bar"
              role="progressbar"
              style="width: 80%"
              aria-valuenow="0"
              aria-valuemin="0"
              aria-valuemax="100"
            ></div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 mb-30">
      <div class="pd-20 card-box height-100-p">
        <div class="profile-photo">
          <img
            src="{% static 'vendors/images/photo1.jpg' %}"
            alt=""
            class="avatar-photo"
          />
          <div
            class="modal fade"
            id="modal"
            tabindex="-1"
            role="dialog"
            aria-labelledby="modalLabel"
            aria-hidden="true"
          >
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-body pd-5">
                  <div class="img-container">
                    <img
                      id="image"
                      src="vendors/images/photo2.jpg"
                      alt="Picture"
                    />
                  </div>
                </div>
                <div class="modal-footer">
                  <input type="submit" value="Update" class="btn btn-primary" />
                  <button
                    type="button"
                    class="btn btn-default"
                    data-dismiss="modal"
                  >
                    Close
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <h5 class="text-center h5 mb-0">Juan Pablo Lara Angulo</h5>
        <p class="text-center text-muted font-14">CAR IV</p>
        <div class="profile-info">
          <h5 class="mb-20 h5 text-blue">Contact Information</h5>
          <ul>
            <li>
              <span>Email Address:</span>
              jlara@lsv-tech.com
            </li>
            <li>
              <span>Phone Number:</span>
              619-229-0054
            </li>
            <li>
              <span>Country:</span>
              America
            </li>
            <li>
              <span>Address:</span>
              1807 Holden Street<br />
              San Diego, CA 92115
            </li>
          </ul>
        </div>
        <div class="profile-social">
          <h5 class="mb-20 h5 text-blue">Social Links</h5>
          <ul class="clearfix">
            <li>
              <a
                href="#"
                class="btn"
                data-bgcolor="#3b5998"
                data-color="#ffffff"
                ><i class="fa fa-facebook"></i
              ></a>
            </li>
            <li>
              <a
                href="#"
                class="btn"
                data-bgcolor="#1da1f2"
                data-color="#ffffff"
                ><i class="fa fa-twitter"></i
              ></a>
            </li>
            <li>
              <a
                href="#"
                class="btn"
                data-bgcolor="#007bb5"
                data-color="#ffffff"
                ><i class="fa fa-linkedin"></i
              ></a>
            </li>
            <li>
              <a
                href="#"
                class="btn"
                data-bgcolor="#f46f30"
                data-color="#ffffff"
                ><i class="fa fa-instagram"></i
              ></a>
            </li>
            <li>
              <a
                href="#"
                class="btn"
                data-bgcolor="#c32361"
                data-color="#ffffff"
                ><i class="fa fa-dribbble"></i
              ></a>
            </li>
            <li>
              <a
                href="#"
                class="btn"
                data-bgcolor="#3d464d"
                data-color="#ffffff"
                ><i class="fa fa-dropbox"></i
              ></a>
            </li>
            <li>
              <a
                href="#"
                class="btn"
                data-bgcolor="#db4437"
                data-color="#ffffff"
                ><i class="fa fa-google-plus"></i
              ></a>
            </li>
            <li>
              <a
                href="#"
                class="btn"
                data-bgcolor="#bd081c"
                data-color="#ffffff"
                ><i class="fa fa-pinterest-p"></i
              ></a>
            </li>
            <li>
              <a
                href="#"
                class="btn"
                data-bgcolor="#00aff0"
                data-color="#ffffff"
                ><i class="fa fa-skype"></i
              ></a>
            </li>
            <li>
              <a
                href="#"
                class="btn"
                data-bgcolor="#00b489"
                data-color="#ffffff"
                ><i class="fa fa-vine"></i
              ></a>
            </li>
          </ul>
        </div>
        <div class="profile-skills">
          <h5 class="mb-20 h5 text-blue">Key Skills</h5>
          <h6 class="mb-5 font-14">HTML</h6>
          <div class="progress mb-20" style="height: 6px">
            <div
              class="progress-bar"
              role="progressbar"
              style="width: 90%"
              aria-valuenow="0"
              aria-valuemin="0"
              aria-valuemax="100"
            ></div>
          </div>
          <h6 class="mb-5 font-14">Css</h6>
          <div class="progress mb-20" style="height: 6px">
            <div
              class="progress-bar"
              role="progressbar"
              style="width: 70%"
              aria-valuenow="0"
              aria-valuemin="0"
              aria-valuemax="100"
            ></div>
          </div>
          <h6 class="mb-5 font-14">jQuery</h6>
          <div class="progress mb-20" style="height: 6px">
            <div
              class="progress-bar"
              role="progressbar"
              style="width: 60%"
              aria-valuenow="0"
              aria-valuemin="0"
              aria-valuemax="100"
            ></div>
          </div>
          <h6 class="mb-5 font-14">Bootstrap</h6>
          <div class="progress mb-20" style="height: 6px">
            <div
              class="progress-bar"
              role="progressbar"
              style="width: 80%"
              aria-valuenow="0"
              aria-valuemin="0"
              aria-valuemax="100"
            ></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <!-- Basic Page Info -->
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock %}</title>

    <!-- Site favicon -->
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="{% static 'vendors/images/apple-touch-icon.png' %}"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="{% static 'vendors/images/favicon-32x32.png' %}"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="{% static 'vendors/images/favicon-16x16.png' %}"
    />

    <!-- Mobile Specific Metas -->
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, maximum-scale=1"
    />

    <!-- Google Font -->
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap"
      rel="stylesheet"
    />
    <!-- CSS -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'vendors/styles/core.css' %}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'vendors/styles/icon-font.min.css' %}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'src/plugins/datatables/css/dataTables.bootstrap4.min.css' %}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'src/plugins/datatables/css/responsive.bootstrap4.min.css' %}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'vendors/styles/style.css' %}"
    />

    <!-- Datatable -->
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css"
    />
  </head>
  <body>
    <div class="pre-loader">
      <div class="pre-loader-box">
        <div class="loader-logo">
          <img src="{% static 'vendors/images/deskapp-logo.svg' %}" alt="" />
        </div>
        <div class="loader-progress" id="progress_div">
          <div class="bar" id="bar1"></div>
        </div>
        <div class="percent" id="percent1">0%</div>
        <div class="loading-text">Loading...</div>
      </div>
    </div>

    <div class="header">
      <div class="header-left d-flex justify-content-end">
        <div class="menu-icon dw dw-menu"></div>
        <a href="index.html">
          <img
            src="{% static 'vendors/images/deskapp-logo.svg' %}"
            alt=""
            class="dark-logo ml-2"
          />
        </a>
      </div>
    </div>

    <div class="left-side-bar">
      <div class="brand-logo">
        <a href="index.html">
          <img
            src="{% static 'vendors/images/deskapp-logo.svg' %}"
            alt=""
            class="dark-logo"
          />
          <img
            src="{% static 'vendors/images/deskapp-logo-white.svg' %}"
            alt=""
            class="light-logo"
          />
        </a>
        <div class="close-sidebar" data-toggle="left-sidebar-close">
          <i class="ion-close-round"></i>
        </div>
      </div>
      <div class="menu-block customscroll">
        <div class="sidebar-menu">
          <ul id="accordion-menu">
            <li>
              <a href="/" class="dropdown-toggle no-arrow">
                <span class="micon dw dw-house-1"></span
                ><span class="mtext">Home</span>
              </a>
            </li>
            <li>
              <a
                href="{% url 'reports:index' %}"
                class="dropdown-toggle no-arrow"
              >
                <span class="micon dw dw-bar-chart-1"></span
                ><span class="mtext">Reports</span>
              </a>
            </li>
            <li>
              <a
                href="{% url 'reports:about' %}"
                class="dropdown-toggle no-arrow"
              >
                <span class="micon dw dw-user-12"></span
                ><span class="mtext">About Us</span>
              </a>
            </li>
            <li>
              <a href="invoice.html" class="dropdown-toggle no-arrow">
                <span class="micon dw dw-invoice"></span
                ><span class="mtext">Invoice</span>
              </a>
            </li>
            <li>
              <div class="dropdown-divider"></div>
            </li>
            <li>
              <div class="sidebar-small-cap">Extra</div>
            </li>
            <li>
              <a href="javascript:;" class="dropdown-toggle">
                <span class="micon dw dw-edit-2"></span
                ><span class="mtext">Documentation</span>
              </a>
              <ul class="submenu">
                <li><a href="introduction.html">Introduction</a></li>
                <li><a href="getting-started.html">Getting Started</a></li>
                <li><a href="color-settings.html">Color Settings</a></li>
                <li>
                  <a href="third-party-plugins.html">Third Party Plugins</a>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="mobile-menu-overlay"></div>

    <!-- main content -->
    <div class="main-container">
      <div class="pd-ltr-20">
        <!-- main content start-->
        {% block content %} {% endblock %}
        <!-- main content end-->

        <!-- footer -->
        <div class="footer-wrap pd-20 mb-20 card-box">
          DeskApp - Bootstrap 4 Admin Template By
          <a href="https://github.com/dropways" target="_blank"
            >Ankit Hingarajiya</a
          >
        </div>
      </div>
    </div>
    <!-- js -->
    <script src="{% static 'vendors/scripts/core.js' %}"></script>
    <script src="{% static 'vendors/scripts/script.min.js' %}"></script>
    <script src="{% static 'vendors/scripts/process.js' %}"></script>
    <script src="{% static 'vendors/scripts/layout-settings.js' %}"></script>
    <script src="{% static 'src/plugins/apexcharts/apexcharts.min.js' %}"></script>
    <script src="{% static 'src/plugins/datatables/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'src/plugins/datatables/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'src/plugins/datatables/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'src/plugins/datatables/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="{% static 'vendors/scripts/dashboard.js' %}"></script>

    <script
      type="text/javascript"
      charset="utf8"
      src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"
    ></script>

    <script type="text/javascript">
      $(document).ready(function () {
        $("#tablax").DataTable();
      });
    </script>
  </body>
</html>

templates/index.html
{% extends 'base.html' %} {% load static %} {% block title %}Reports - Covid
Report{% endblock %} {% block content %}

<div class="min-height-200px">
  <div class="pd-20 card-box mb-30">
    <table id="tablax" class="table-responsive">
      <thead>
        <tr>
          <th>Country</th>
          <th>Total Cases</th>
          <th>New Cases</th>
          <th>Total Deaths</th>
          <th>New Deaths</th>
          <th>Total Recovered</th>
          <th>New Recovered</th>
          <th>Active Cases</th>
          <th>Serious, Critical</th>
          <th>Tot Cases / 1M pop</th>
          <th>Deaths / 1M pop</th>
          <th>Total Tests</th>
          <th>Test / 1M pop</th>
          <th>Population</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for register in registers %}
        <tr>
          <td>{{register.country}}</td>
          <td>{{register.total_cases}}</td>
          <td>{{register.new_cases}}</td>
          <td>{{register.total_deaths}}</td>
          <td>{{register.new_deaths}}</td>
          <td>{{register.total_recovered}}</td>
          <td>{{register.new_recovered}}</td>
          <td>{{register.active_cases}}</td>
          <td>{{register.serious_critical}}</td>
          <td>{{register.total_cases_per_million}}</td>
          <td>{{register.deaths_per_million}}</td>
          <td>{{register.total_tests}}</td>
          <td>{{register.test_per_million}}</td>
          <td>{{register.population}}</td>
          <td class="row">
            <a href="{% url 'reports:update' register.id %}" class="btn btn-primary col mb-2">Edit</a>
            <a href="{% url 'reports:delete' register.id %}" class="btn btn-danger col">Delete</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

templates/update.html
{% extends 'base.html' %} {% load static %} {% block title %}Update - Covid
Report {% endblock %} {% block content %}
<div class="min-height-200px">
  <div class="form-row justify-content-center">
    <div class="form-group col-md-6">
      <form class="form" method="POST">
        {% csrf_token %} {{ form.as_p }}
        <button type="button" class="btn btn-primary">Update</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}